# yaml-language-server: $schema=schemas/TrainConfig.json

# A config file to test training.
# Used in automated tests.
debug: false
disk_mode: true
pin_mem: true
save_freq: 5
epochs: 1
batch_size: 1
preemptible: false
learning_rate: 0.0001
scheduler: null
loss: mse
finetune: false
resume_ckpt_path: null
inference_epochs: [-1]
data_percent: 1.0
train_time:
  start: "1975-08-15"
  end: "1975-09-25"
val_time:
  start: "1975-10-20"
  end: "1975-11-20"
inference_times:
  - start: "1975-10-30"
    end: "1975-12-20"
data_stride: [1]
steps: [2]
step_transition: []
backend: auto

experiment:
  name: test
  rand_seed: 15
  base_output_dir: .LOCAL
  wandb:
    mode: disabled
    project: ocean-emulators
    entity: m2lines
    group: samudra-train-om4
  prognostic_vars_key: thermo_dynamic_5
  boundary_vars_key: tau_hfds
  data_root: .data_cache/
data:
  data_location: data.zarr
  data_means_location: means.nc
  data_stds_location: stds.nc
  scaling_residuals_file: null
  num_workers: 4
  hist: 0


model:
  pred_residuals: false
  last_kernel_size: 3
  pad: "circular"
  unet:
    ch_width: [2, 2]
    dilation: [1, 2]
    n_layers: [1, 1]

    core_block:
      block_type: "conv_next_block"
      kernel_size: 3
      activation: "capped_gelu"
      upscale_factor: 2
      norm: "batch"

    down_sampling_block: "avg_pool"
    up_sampling_block: "bilinear_upsample"

