# yaml-language-server: $schema=schemas/TrainConfig.json

debug: false
disk_mode: true
pin_mem: true
save_freq: 5
epochs: 120
batch_size: 3
learning_rate: 0.0001
scheduler: {type: cosine}
loss: mse
finetune: false
resume_ckpt_path: null
inference_epochs: [-1]
data_percent: 1.0
train_time:
  start: "0151-01-06"
  end: "0306-01-01"
val_time:
  start: "0306-01-01"
  end: "0311-01-01"
inference_times:
  - start: "0151-01-06"
    end: "0171-01-11"
  - start: "0171-01-06"
    end: "0191-01-11"
  - start: "0191-01-06"
    end: "0211-01-11"
  - start: "0211-01-06"
    end: "0231-01-11"
  - start: "0231-01-06"
    end: "0251-01-11"
  - start: "0251-01-06"
    end: "0271-01-11"
  - start: "0271-01-06"
    end: "0291-01-11"
  - start: "0291-01-06"
    end: "0311-01-11"
data_stride: [1]
steps: [4]
step_transition: []
backend: auto

experiment:
  name: cm4_samudra
  rand_seed: 5
  base_output_dir: train
  data_root: /pscratch/sd/s/suryad/data
  wandb:
    mode: online
    project: ocean-emulator
    entity: ai2cm
    group: samudra-train-2in2out
  prognostic_vars_key: thermo_dynamic_all
  boundary_vars_key: tau_hfds

data: !include data/cm4.yaml

model:
  pred_residuals: false
  last_kernel_size: 3
  pad: "circular"

  unet:
    ch_width: [200, 250, 300, 400]
    dilation: [1, 2, 4, 8]
    n_layers: [1, 1, 1, 1]

    core_block:
      block_type: "conv_next_block"
      kernel_size: 3
      activation: "capped_gelu"
      upscale_factor: 4
      norm: "batch"

    down_sampling_block: "avg_pool"
    up_sampling_block: "bilinear_upsample"

  corrector:
    non_negative_corrector_names:
      - "so"