# yaml-language-server: $schema=schemas/TrainConfig.json

debug: false
disk_mode: true
pin_mem: true
save_freq: 5
epochs: 70
batch_size: 4
learning_rate: 0.0002
scheduler: {type: cosine}
loss: mse
finetune: false
resume_ckpt_path: null
inference_epochs: [-1]
data_percent: 1.0
train_time:
  start: "1975-01-03"
  end: "2013-10-05"
val_time:
  start: "2013-10-05"
  end: "2014-10-05"
inference_times:
  - start: "1975-01-03"
    end: "1985-01-03"
  - start: "1985-01-03"
    end: "1995-01-03"
  - start: "1995-01-03"
    end: "2005-01-03"
  - start: "2004-10-05"
    end: "2014-10-05"
data_stride: [1]
steps: [4]
step_transition: []
backend: auto

experiment:
  name: om4_samudra
  rand_seed: 5
  base_output_dir: train
  data_root: /pscratch/sd/s/suryad/data
  wandb:
    mode: online
    project: ocean-emulators
    entity: m2lines
    group: samudra-train-om4
  prognostic_vars_key: thermo_all
  boundary_vars_key: tau_hfds_hfds_anom

data: !include data/om4_ohc.yaml

model:
  pred_residuals: false
  last_kernel_size: 3
  pad: "circular"

  unet:
    ch_width: [200, 250, 300, 400]
    dilation: [1, 2, 4, 8]
    n_layers: [1, 1, 1, 1]

    core_block:
      block_type: "conv_next_block"
      kernel_size: 3
      activation: "capped_gelu"
      upscale_factor: 4
      norm: "batch"

    down_sampling_block: "avg_pool"
    up_sampling_block: "bilinear_upsample"

  corrector:
    non_negative_corrector_names: null
    ocean_heat_corrector: true