# yaml-language-server: $schema=../../schemas/EvalConfig.json
# Evaluation for: helmholtzfull_mae_grad_w01_25lev
# Category: helmholtz_full

debug: false
save_zarr: true
disk_mode: true
ckpt_path: ./outputs/helmholtzfull_mae_grad_w01_25lev/checkpoints/ckpt_ema_epoch_040.pt
inference_time:
  start: '2025-01-01'
  end: '2025-12-31'
num_model_steps_forward: 10
backend: auto
experiment:
  name: helmholtzfull_mae_grad_w01_25lev_eval
  rand_seed: 15
  base_output_dir: ./outputs
  wandb:
    mode: disabled
    project: ocean-emulators
    entity: m2lines
    group: helmholtz_full-eval
  prognostic_vars_key: optimized_helmholtz_25
  boundary_vars_key: minimal_forcing
  data_root: /scratch/cimes/maximek/INMOS/processed_data/MOM6_CobaltDG_Clim_FULL
data:
  data_location: bgc_data.zarr
  data_means_location: bgc_means.zarr
  data_stds_location: bgc_stds.zarr
  scaling_residuals_file: null
  num_workers: 8
  persistent_workers: true
  prefetch_factor: 8
  hist: 1
  concurrent_compute: true
model:
  checkpointing: all
  pred_residuals: false
  last_kernel_size: 3
  pad: constant
  unet:
    ch_width:
    - 160
    - 220
    - 300
    dilation:
    - 1
    - 2
    - 4
    n_layers:
    - 1
    - 1
    - 1
    core_block:
      block_type: conv_next_block
      kernel_size: 3
      activation: capped_gelu
      upscale_factor: 2
      norm: batch
    down_sampling_block: avg_pool
    up_sampling_block: bilinear_upsample
  corrector:
    non_negative_corrector_names: null
    ocean_heat_corrector: false
